### ISSUE TITLE
There is a way to ping only one ip address?

### ISSUE THREAD

**Issue by MkLHX** [andrey-ushakov/ping_discover_network#1]
Hi, thanks for the lib, i tested it and it's nice!
But on my case i just have to ping test one known ip address on my network.
I read code, the doc and examples but i not found any way to run ping on ip like "192.168.0.10"

**Comment by wwandreww** [comment]
Hi Mickael,

This lib allow you to find all the network devices in a given subnet.
In your case maybe all you need is to create a socket ?

```
Socket.connect("192.168.0.10", 9100).then((Socket socket) {
      print("Connected");
   }).catchError((AsyncError e) {
      print("Unable to connect: $e");
   });
```

**Comment by MkLHX** [comment]
Thanks for shared code, i looking for this kind of feature and you give me the right speediest answer just now. I'm going to test it.
Thx.
