### ISSUE TITLE
more details information

### ISSUE THREAD

**Issue by LtotheWT** [andrey-ushakov/ping_discover_network#4]
Hi andrey, is it possible to know from the ip address that the connected device is apple or android ?

**Comment by wwandreww** [comment]
Hi,
Nope, unfortunately that's not possible. Using this package you can only find active/connected devices

**Comment by LtotheWT** [comment]
if in that case how can i know the ip address is from printer ?

**Comment by wwandreww** [comment]
Because a very common port for printers is 9100. But yes, you can't be 100% sure what's the device is connected to your network. This package tries to establish a socket connection to every address to find active devices.

**Comment by LtotheWT** [comment]
ahh okay, thx for the reply and this awesome package.
