### ISSUE TITLE
There are 10 devices here under the router,but only router can be found.

### ISSUE THREAD

**Issue by iperfectapp** [andrey-ushakov/ping_discover_network#5]
![image](https://user-images.githubusercontent.com/3021764/69733048-ad004080-1167-11ea-8a34-ffd4f2ff50e0.png)

Error:Unhandled exception:\nBad state: Stream has already been listened to.

**Comment by Azzeccagarbugli** [comment]
I have the same issue and I don't know why this is happening.

With the following command `nmap -sP 192.168.0.1/23 ` on my Linux distribution I'm able to find all the devices connected to the network but when it comes to the following snippet of code: 

```
final stream = NetworkAnalyzer.discover(subnet, port);

    stream.listen((NetworkAddress addr) {
      if (addr.exists) {
        print('Found device: ${addr.ip}');
        setState(() {
          devices.add(addr.ip);
          found = devices.length;
        });
      }
    })
```

None of my devices are showing up except for my router.

I even tried with the `discover2` method but nothing is changing. 

I really would like to understand what's going on. Thanks a lot!
