### ISSUE TITLE
release / debug : NetworkAnalyzer.discover2 doesn't detect ip

### ISSUE THREAD

**Issue by FredMour** [andrey-ushakov/ping_discover_network#7]
Hi,

I am trying "NetworkAnalyzer.discover2 in the port 22 / ssh" with Android10

It s working fine with the debug version, but when I try to "release" an apk and install it on the phone, the NetworkAnalyzer.discover2 doesn't detect anything ( the same is working in debug )

Does it miss some network authorization? 

Best Regards,
Frédéric

**Comment by cosismo** [comment]
Same problem here. It is a missed permission in AndroidManifest

Filled a PR:
https://github.com/andrey-ushakov/ping_discover_network/pull/9

**Comment by wwandreww** [comment]
PR merged, thank you @cosismo
